### PR TITLE
Grab metadata URL from the session

### PR DESCRIPTION
**Pull request by lukegotszling**

### CODE REVIEW

**Comment by FabioFleitas** [comment]
❓ So you're getting it from a logged-in user session?

**Comment by lukegotszling** [comment]
@FabioFleitas from a logged-out user session (though they can be logged-in as well).

**Comment by FabioFleitas** [comment]
So would this work for someone visiting the page for the first time?

So in general what I was thinking was that in the app, the `Company` would have a field with the URL in it. And so when someone puts their email in the form for SSO beforehand, we can pull the `Person` and the `Company` and pull the URL from there. Not sure if that's how you were thinking about it as well?

**Comment by lukegotszling** [comment]
@FabioFleitas yes, it would work for someone visiting for the first time. Yes, that is exactly how I've implemented it.

**Review by FabioFleitas — APPROVED** [review]

**Pull request merged**
